# Generated by Django 5.2.4 on 2025-07-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='ID del precio en Stripe (optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='ID Stripe Product', max_length=255, null=True, unique=True),
        ),
    ]
