# Generated by Django 5.2.4 on 2025-07-11 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
