# Generated by Django 5.2.4 on 2025-07-19 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_first_name', models.CharField(max_length=30)),
                ('author_last_name', models.CharField(max_length=30)),
                ('author_bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_format', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200)),
                ('book_synopsis', models.TextField()),
                ('book_number_pages', models.IntegerField()),
                ('book_published', models.DateField()),
                ('book_ISBN', models.CharField(max_length=13)),
                ('book_sku', models.CharField(max_length=12)),
                ('book_image', models.ImageField(upload_to='books/')),
                ('book_price', models.IntegerField()),
                ('book_stock_quantity', models.IntegerField()),
                ('book_slug', models.SlugField(max_length=200, unique=True)),
                ('book_status', models.CharField(choices=[('A', 'ACTIVE'), ('F', 'OUT_OF_STOCK')], default='A', max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='catalog.author')),
                ('category', models.ManyToManyField(related_name='books', to='catalog.category')),
                ('formats', models.ManyToManyField(related_name='books', to='catalog.format')),
                ('languages', models.ManyToManyField(related_name='books', to='catalog.language')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='catalog.publisher')),
            ],
        ),
    ]
