# Generated by Django 5.2.4 on 2025-07-15 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_description',
        ),
    ]
